import assert from "node:assert/strict";

// Real app/API checks: removing the route, disabling invalidation, swapping
// thresholds or losing a pending draft must fail these observable behaviours.
export async function checkBudgets({ send, evaluate, text, waitText, until, click, fill, apiRequest, follow: followLink, ui, categories, capture }) {
  async function follow(href) {
    await followLink(href);
    await waitText(href === "/budgets" ? "Budget Bulanan" : "Tambah Transaksi");
  }
  const food = categories.find((item) => item.name === "Makanan").id;
  const transport = categories.find((item) => item.name === "Transport").id;
  const fun = categories.find((item) => item.name === "Hiburan").id;
  const salary = categories.find((item) => item.name === "Gaji").id;
  assert.ok(await evaluate("Boolean(document.querySelector('a[href=\"/budgets\"]'))"), "Budget navigation is not implemented");
  await follow("/budgets");
  await waitText("Belum ada budget");
  await click("Tambah Budget");
  await click("Simpan budget");
  assert.equal(await evaluate("document.activeElement.name"), "category_id");
  assert.equal(await evaluate(`Boolean(document.querySelector('[name=category_id] option[value="${salary}"]'))`), false);
  await fill("period", "2026-07");
  await fill("category_id", String(food));
  await fill("amount_rupiah", "0");
  await click("Simpan budget");
  assert.equal(await evaluate("document.activeElement.name"), "amount_rupiah");
  await fill("amount_rupiah", "400");
  await click("Simpan budget");
  await until(async () => !await evaluate("Boolean(document.querySelector('[name=period]'))"), "budget create closes form");
  await fill("budget-filter-period", "2026-07");
  await waitText("75%");
  await until(async () => await evaluate("document.activeElement.name === 'budget-filter-period' || document.activeElement.textContent.trim() === 'Tambah Budget'"), "budget focus after create");
  const foodRow = () => evaluate("document.querySelector('[aria-label=\"Budget Makanan\"]').innerText");
  assert.ok((await foodRow()).includes("Normal"));
  for (const [category, amount] of [[transport, "125"], [fun, "40"]]) {
    await click("Tambah Budget");
    await fill("category_id", String(category));
    await fill("amount_rupiah", amount);
    await click("Simpan budget");
    await until(async () => !await evaluate("Boolean(document.querySelector('[name=period]'))"), "budget save closes form");
  }
  await apiRequest("/transactions", "POST", { category_id: fun, type: "expense", amount_rupiah: "50", date: "2026-07-05", description: "Budget fixture" });
  // Reload to pick up test-only API writes. Production mutations below use SPA.
  const beforeFixtureReload = await evaluate("performance.timeOrigin");
  await send("Page.reload");
  await until(async () => await evaluate(`performance.timeOrigin !== ${beforeFixtureReload} && Boolean(document.querySelector('[name=budget-filter-period]'))`), "reloaded budget period control");
  await fill("budget-filter-period", "2026-07");
  await waitText("125%");
  await waitText("Mendekati batas");
  assert.ok((await text()).replace(/\s+/g, " ").includes("-Rp 10"));
  assert.deepEqual(await evaluate("[...document.querySelectorAll('progress')].map(el => el.value)"), [75, 80, 100]);
  assert.ok(await evaluate("document.querySelector('[aria-label=\"Progress budget Hiburan\"]').getAttribute('aria-valuetext').includes('125%')"));
  console.log("PASS budget create, expense-only validation, 75/80/125% and capped accessible bars");

  await evaluate("{ const button = document.querySelector('[aria-label=\"Edit budget Makanan\"]'); button.focus(); button.click(); }");
  await fill("amount_rupiah", "500");
  await click("Simpan perubahan");
  await waitText("60%");
  await until(async () => await evaluate("document.activeElement.getAttribute('aria-label') === 'Edit budget Makanan'"), "budget edit restores focus");
  await evaluate("{ const button = document.querySelector('[aria-label=\"Edit budget Makanan\"]'); button.focus(); button.click(); }");
  await fill("amount_rupiah", "400");
  await click("Simpan perubahan");
  await waitText("75%");

  await click("Tambah Budget");
  await fill("category_id", String(food));
  await fill("amount_rupiah", "9999999999999");
  await click("Simpan budget");
  await waitText("konflik");
  assert.equal(await evaluate("document.querySelector('[name=amount_rupiah]').value"), "9999999999999");
  // Change period but keep the draft; 422 errors focus their corresponding field.
  await fill("period", "2026-08");
  await evaluate("window.realFetch = window.fetch; window.fetch = (...args) => args[1]?.method === 'POST' ? Promise.resolve(new Response(JSON.stringify({detail:[{loc:['body','amount_rupiah']}]}),{status:422})) : window.realFetch(...args)");
  await click("Simpan budget");
  await waitText("Nominal ditolak server");
  assert.equal(await evaluate("document.activeElement.name"), "amount_rupiah");
  await evaluate("window.fetch = (...args) => args[1]?.method === 'POST' ? Promise.reject(new TypeError('offline')) : window.realFetch(...args)");
  await click("Simpan budget");
  await waitText("Tidak dapat terhubung");
  assert.equal(await evaluate("document.querySelector('[name=amount_rupiah]').value"), "9999999999999");
  await fill("amount_rupiah", "400");
  await evaluate("window.budgetRequests = 0; window.fetch = (...args) => { if (args[1]?.method !== 'POST') return window.realFetch(...args); window.budgetRequests++; return new Promise((yes,no) => setTimeout(() => window.realFetch(...args).then(yes,no),400)); }; document.querySelector('form').requestSubmit(); document.querySelector('form').requestSubmit(); document.querySelector('form').requestSubmit()");
  await waitText("Menyimpan…");
  assert.equal(await evaluate("document.querySelector('[type=submit]').disabled"), true);
  assert.equal(await evaluate("document.querySelector('[name=budget-filter-period]').disabled"), true);
  await until(async () => !await evaluate("Boolean(document.querySelector('[name=period]'))"), "budget pending save closes once");
  assert.equal(await evaluate("window.budgetRequests"), 1);
  await evaluate("window.fetch = window.realFetch");
  await fill("budget-filter-period", "2026-08");
  await waitText("0%");
  await fill("budget-filter-period", "2026-07");
  await waitText("75%");
  console.log("PASS budget PATCH, conflict/server/network draft retention, focus and double-submit guard");

  await follow("/transactions");
  await click("Tambah Transaksi");
  await fill("date", "2026-07-10");
  await fill("category_id", String(food));
  await fill("amount_rupiah", "100");
  await fill("description", "Budget mutation");
  await click("Simpan transaksi");
  await until(async () => !await evaluate("Boolean(document.querySelector('[name=date]'))"), "budget transaction create closes");
  await follow("/budgets");
  await fill("budget-filter-period", "2026-07");
  await until(async () => (await foodRow()).includes("100%") && (await foodRow()).includes("Over budget"), "100% is over budget after transaction create");
  await follow("/transactions");
  await fill("filter-month", "2026-07");
  await waitText("Budget mutation");
  await evaluate("document.querySelector('[aria-label=\"Edit transaksi Budget mutation\"]').click()");
  await fill("amount_rupiah", "200");
  await click("Simpan perubahan");
  await until(async () => !await evaluate("Boolean(document.querySelector('[name=date]'))"), "budget transaction edit closes");
  await follow("/budgets");
  await fill("budget-filter-period", "2026-07");
  await until(async () => (await foodRow()).includes("125%"), "cached budget updates after expense edit");
  await follow("/transactions");
  await fill("filter-month", "2026-07");
  await waitText("Budget mutation");
  await evaluate("document.querySelector('[aria-label=\"Edit transaksi Budget mutation\"]').click()");
  await fill("date", "2026-08-01");
  await click("Simpan perubahan");
  await until(async () => !await evaluate("Boolean(document.querySelector('[name=date]'))"), "transaction move closes");
  await follow("/budgets");
  await fill("budget-filter-period", "2026-07");
  await until(async () => (await foodRow()).includes("75%"), "old month refreshes after move");
  await fill("budget-filter-period", "2026-08");
  await waitText("50%");
  await follow("/transactions");
  await fill("filter-month", "2026-08");
  await waitText("Budget mutation");
  await evaluate("document.querySelector('[aria-label=\"Hapus transaksi Budget mutation\"]').click()");
  await click("Hapus transaksi");
  await until(async () => !await evaluate("Boolean(document.querySelector('dialog'))"), "budget transaction delete closes");
  await follow("/budgets");
  await fill("budget-filter-period", "2026-08");
  await waitText("0%");
  console.log("PASS cached budgets refresh after transaction create/edit/move/delete across periods");

  await fill("budget-filter-period", "2026-07");
  await waitText("125%");
  await evaluate("window.realFetch = window.fetch; window.fetch = (...args) => String(args[0]).includes('/budgets/status') ? Promise.reject(new TypeError('offline budget')) : window.realFetch(...args)");
  await fill("budget-filter-period", "2026-08");
  await waitText("Budget gagal dimuat");
  assert.equal((await text()).includes("Belum ada budget"), false);
  assert.equal(await evaluate("document.querySelectorAll('progress').length"), 0);
  await evaluate("window.fetch = window.realFetch");
  await click("Coba lagi budget");
  await waitText("0%");
  await fill("budget-filter-period", "");
  assert.equal(await evaluate("[...document.querySelectorAll('button')].find(el => el.textContent.trim()==='Tambah Budget').disabled"), true);
  await fill("budget-filter-period", "2026-07");
  await waitText("125%");
  await evaluate("{ const button = document.querySelector('[aria-label=\"Hapus budget Hiburan\"]'); button.focus(); button.click(); }");
  await waitText("Hapus budget?");
  await click("Batal");
  await until(async () => await evaluate("document.activeElement.getAttribute('aria-label') === 'Hapus budget Hiburan'"), "budget delete cancel focus");
  await evaluate("{ const button = document.querySelector('[aria-label=\"Hapus budget Hiburan\"]'); button.focus(); button.click(); }");
  await evaluate("window.fetch = (...args) => args[1]?.method === 'DELETE' ? Promise.resolve(new Response('{}',{status:409})) : window.realFetch(...args)");
  await click("Hapus budget");
  await waitText("konflik");
  assert.equal(await evaluate("Boolean(document.querySelector('dialog[open]'))"), true);
  await evaluate("window.fetch = window.realFetch");
  await click("Hapus budget");
  await until(async () => !await evaluate("Boolean(document.querySelector('dialog'))"), "budget delete retry closes");
  await until(async () => await evaluate("document.activeElement.textContent.trim() === 'Tambah Budget'"), "budget delete fallback focus");
  assert.equal(await evaluate("Boolean(document.querySelector('[aria-label=\"Budget Hiburan\"]'))"), false);
  assert.ok((await apiRequest("/transactions?category_id=" + fun)).total > 0, "budget delete must not delete transactions");
  console.log("PASS budget fetch error/retry hides stale amounts, invalid period, delete cancel/error/retry");

  const fault = await send("Page.addScriptToEvaluateOnNewDocument", { source: "window.realFetch=window.fetch; window.fetch=(...args)=>String(args[0]).includes('/categories') ? Promise.reject(new TypeError('offline categories')) : new Promise((yes,no)=>setTimeout(()=>window.realFetch(...args).then(yes,no),400));" });
  await send("Page.navigate", { url: `${ui}/budgets` });
  await waitText("Memuat budget");
  await waitText("Kategori gagal dimuat");
  await click("Tambah Budget");
  assert.equal(await evaluate("document.querySelector('[type=submit]').disabled"), true);
  await fill("amount_rupiah", "123456");
  await evaluate("window.fetch = window.realFetch");
  await click("Coba lagi kategori");
  await until(async () => !await evaluate("document.querySelector('[type=submit]').disabled"), "category recovery enables budget form");
  assert.equal(await evaluate("document.querySelector('[name=amount_rupiah]').value"), "123456");
  await click("Batal");
  await send("Page.removeScriptToEvaluateOnNewDocument", { identifier: fault.identifier });
  await fill("budget-filter-period", "0001-01");
  await waitText("Belum ada budget");
  await fill("budget-filter-period", "2026-07");
  await waitText("75%");
  await apiRequest("/budgets", "POST", { category_id: fun, amount_rupiah: "40", month: 7, year: 2026 });
  await fill("budget-filter-period", "2026-09");
  await waitText("Belum ada budget");
  const beforeReload = await evaluate("performance.timeOrigin");
  await send("Page.reload");
  // Header/controls also exist in the old document. Wait for the new document
  // and React's mounted control rather than racing a pending reload.
  await until(async () => await evaluate(`performance.timeOrigin !== ${beforeReload} && Boolean(document.querySelector('[name=budget-filter-period]'))`), "reloaded budget period control");
  await fill("budget-filter-period", "2026-07");
  await waitText("125%");
  await evaluate("window.scrollTo(0,0)");
  await capture("tiny-budget.png", 320, 844);
  assert.equal(await evaluate("[...document.querySelectorAll('header a')].filter(el => el.getBoundingClientRect().width > 0).every(el => { const r = el.getBoundingClientRect(); return r.left >= 0 && r.right <= 320; })"), true, "all three navigation destinations fit at 320px");
  await capture("desktop-budget.png", 1366, 900);
  await capture("mobile-budget.png", 390, 844);
  await click("Tambah Budget");
  await capture("mobile-budget-form.png", 390, 844);
  await click("Batal");
  console.log("PASS budget loading/categories recovery, empty/ancient period, reload and desktop/mobile captures");
}
